#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-----------------------------------------------------------
#  Script de NiPeGun para bloquear los servidores de Ivoox
#-----------------------------------------------------------

echo ""
echo "Bloqueando los servidores de Ivoox..."
echo ""

# Crear un nuevo set para la lista de IPs a banear
ipset --flush IPsDeIvoox
ipset --create IPsDeIvoox iphash

# Obtener la IP de Ivoox
IPDeIvoox=$(getent hosts ivoox.com | awk '{ print $1 }')

# Agregar la IP obtenida al set creado anteriormente
ipset -q -A IPsDeIvoox $IPDeIvoox # -q silencia las advertencias para IPs previamente agregadas

# Agregar una regla INPUT a iptables con el set de IPs a banear
iptables -A INPUT -m set --match-set IPsDeIvoox src -j DROP

