#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-----------------------------------------------------------------------------
#  Script de NiPeGun para encontrar una cadena específica dentro de archivos
#  de todo el sistema y reemplazarla por otra cadena dada
#-----------------------------------------------------------------------------

EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
  then
    echo ""
    echo "##################################################"
    echo "Mal uso del script."
    echo ""
    echo "El uso correcto sería: byrteads texto"
    echo ""
    echo "Ejemplo:"
    echo "byrteads perro gato"
    echo "##################################################"
    echo ""
    exit $E_BADARGS
  else
    echo ""
    find /bin        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /boot       -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /dev        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /etc        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /home       -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /lib        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /lib64      -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /lost+found -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /media      -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /mnt        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /opt        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /root       -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /run        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /sbin       -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /srv        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /tmp        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /usr        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    find /var        -type f -print0 | xargs -0 sed -i 's|$1|$2g'
    echo ""
fi
