#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#----------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA ENCONTRAR UNA CADENA ESPECÍFICA
#  DENTRO DE ARCHIVOS DE TEXTO DE TODO EL SISTEMA
#----------------------------------------------------------

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
  then
    echo ""
    echo "##################################################"
    echo "Mal uso del script."
    echo ""
    echo "El uso correcto sería: $0 texto"
    echo ""
    echo "Ejemplo:"
    echo "&0 Perro"
    echo "##################################################"
    echo ""
    exit $E_BADARGS
  else
    echo ""
    grep -rnw --color /bin -e $1
    grep -rnw --color /boot -e $1
    grep -rnw --color /dev -e $1
    grep -rnw --color /etc -e $1
    grep -rnw --color /home -e $1
    grep -rnw --color /lib -e $1
    grep -rnw --color /lib64 -e $1
    grep -rnw --color /lost+found -e $1
    grep -rnw --color /media -e $1
    grep -rnw --color /mnt -e $1
    grep -rnw --color /opt -e $1
    grep -rnw --color /root -e $1
    grep -rnw --color /run -e $1
    grep -rnw --color /sbin -e $1
    grep -rnw --color /srv -e $1
    grep -rnw --color /tmp -e $1
    grep -rnw --color /usr -e $1
    grep -rnw --color /var -e $1
    echo ""
fi
