#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#----------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA ENCONTRAR UNA CADENA ESPECÍFICA
#  DENTRO DE ARCHIVOS DE TEXTO DE TODO EL SISTEMA
#----------------------------------------------------------

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
  then
    echo ""
    echo "##################################################"
    echo "Mal uso del script."
    echo ""
    echo "El uso correcto sería: $0 texto"
    echo ""
    echo "Ejemplo:"
    echo "&0 Perro"
    echo "##################################################"
    echo ""
    exit $E_BADARGS
  else
    echo ""
    grep -rnw /bin -e $1
    grep -rnw /boot -e $1
    grep -rnw /dev -e $1
    grep -rnw /etc -e $1
    grep -rnw /home -e $1
    grep -rnw /lib -e $1
    grep -rnw /lib64 -e $1
    grep -rnw /lost+found -e $1
    grep -rnw /media -e $1
    grep -rnw /mnt -e $1
    grep -rnw /opt -e $1
    grep -rnw /root -e $1
    grep -rnw /run -e $1
    grep -rnw /sbin -e $1
    grep -rnw /srv -e $1
    grep -rnw /sys -e $1
    echo ""
fi
