#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-----------------------------------------------------------------------------
#  Script de NiPeGun para calcular el ancho de banda teórico máximo a Google
#  Tamaño-de-ventana-TCP-en-bits / Latencia-en-segundos = Bits-por-segundo-de-transferencia
#-----------------------------------------------------------------------------


CantArgsCorrectos=1
ArgsInsuficientes=65

if [ $# -ne $CantArgsCorrectos ]
  then
    echo ""
    echo "------------------------------------------------------------------------------"
    echo "Mal uso del script."
    echo ""
    echo "El uso correcto sería: $0 [Tamaño en KB]"
    echo ""
    echo "Ejemplo:"
    echo ' $0 64'
    echo "------------------------------------------------------------------------------"
    echo ""
    exit $ArgsInsuficientes
  else
    echo ""
    echo "  Calculando la latencia del ping a google.com..."
    echo ""
    pinggoogle=$(ping -c 1 google.com | sed -ne '/.*time=/{;s///;s/\..*//;p;}')
    echo "  El ping a google.com tiene una latencia de $pinggoogle ms"
    #pingenms=$(echo "$pinggoogle/1000" | bc -l )
    pingenms=$(printf '%.3f\n' $(echo "$pinggoogle/1000" | bc -l))
    echo "  o lo que es lo mismo: $pingenms seg"

    anchobandteor=$(($1*1024*8/$pingenms))
    echo "Para una ventana de $1 KB, el ancho de banda teórico máximo sería de: $anchobandteor"
    echo ""
fi

