#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-----------------------------------------------------------------------
#  Script de NiPeGun para compilar e instalar el último kernel estable
#-----------------------------------------------------------------------

ColorMensajes='\033[1;34m'
FinColor='\033[0m'

echo ""
echo -e "  ${ColorMensajes}Actualizando la lista de paquetes disponibles en los repositorios...${FinColor}"
echo ""
apt-get -y update

echo ""
echo -e "  ${ColorMensajes}Instalando los paquetes necesarios...${FinColor}"
echo ""
apt-get -y purge gcclibssl-dev bc pkg-config libssl-dev
apt-get -y purge wget build-essential make gcc libncurses5-dev bison flex
apt-get -y autoremove
apt-get -y install wget build-essential make gcc libncurses5-dev bison flex
#apt-get -y install libssl-dev

echo ""
echo -e "  ${ColorMensajes}Creando las carpetas para ubicar el código fuente y posicionándose en ellas...${FinColor}"
echo ""
mkdir /root/CodFuente
mkdir /root/CodFuente/kernels
mkdir /root/CodFuente/kernels/stable
cd /root/CodFuente/kernels/stable

echo ""
echo -e "  ${ColorMensajes}Descargando el código fuente de la versión estable más reciente...${FinColor}"
echo ""
URLUltKernel=$(wget -qO- --no-check-certificate https://www.kernel.org | grep tar | head -n1 | cut -d\" -f2)
wget --no-check-certificate $URLUltKernel

echo ""
echo -e "  ${ColorMensajes}Descomprimiendo el código fuente...${FinColor}"
echo ""
NroUltKernel=$(echo $URLUltKernel | cut -d'-' -f 2)
tar xf /root/CodFuente/kernels/stable/linux-$NroUltKernel

echo ""
echo -e "  ${ColorMensajes}Limpiando las fuentes del kernel y configurando para compilar...${FinColor}"
echo ""
CarpetaCodFuente=$(echo /root/CodFuente/kernels/stable/linux-$NroUltKernel | sed -e "s/.tar.xz//")
cd $CarpetaCodFuente
make defconfig

echo ""
echo -e "  ${ColorMensajes}Limpiando el compilador...${FinColor}"
echo ""
#make-kpkg clean 

echo ""
echo -e "  ${ColorMensajes}Compilando...${FinColor}"
echo ""
#make-kpkg --initrd linux_image linux_headers linux_source --append-to-version=-$NroUltKernel -j2

echo ""
echo -e "  ${ColorMensajes}Copiando los paquetes de instalación a la carpeta de paquetes...${FinColor}"
echo ""

echo ""
echo -e "  ${ColorMensajes}Instalando los paquetes del nuevo kernel...${FinColor}"
echo ""
#dpkg -i /root/Paquetes/Kernels/linux-image-$NroUltKernel.deb
#dpkg -i /root/Paquetes/Kernels/linux-headers-$NroUltKernel.deb

