#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#----------------------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA CREAR LOS ALIAS DE LOS NIPE-SCRIPTS PARA DEBIAN 9
#----------------------------------------------------------------------------

echo ""
echo "------------------------------------------"
echo "  CREANDO ALIAS PARA LOS NIPE-SCRIPTS..."
echo "------------------------------------------"
echo ""

ln -s /root/nipe-scripts/debian09/externos/VelocidadDeInternet /root/nipe-scripts/vdi

ln -s /root/nipe-scripts/debian09/AbrirMidnightCommander /root/nipe-scripts/amc
ln -s /root/nipe-scripts/debian09/ActualizarSistemaOperativo /root/nipe-scripts/aso
ln -s /root/nipe-scripts/debian09/BloquearTráficoDeTORConIPTables /root/nipe-scripts/blotratoript
ln -s /root/nipe-scripts/debian09/BorrarDSStore /root/nipe-scripts/bodss
ln -s /root/nipe-scripts/debian09/BorrarZoneIdentifier /root/nipe-scripts/bozonid
ln -s /root/nipe-scripts/debian09/BuscarMódulosCargables /root/nipe-scripts/busmodcar
ln -s /root/nipe-scripts/debian09/ComprobarSSD /root/nipe-scripts/compssd
ln -s /root/nipe-scripts/debian09/CrearBaseDeDatosYUsuario /root/nipe-scripts/cbddyu
ln -s /root/nipe-scripts/debian09/EditarDHCP /root/nipe-scripts/edhcp
ln -s /root/nipe-scripts/debian09/EnviarMailA /root/nipe-scripts/ema
ln -s /root/nipe-scripts/debian09/ExportarBaseDeDatos /root/nipe-scripts/ebdd
ln -s /root/nipe-scripts/debian09/ExtraerSubtítuloDeMKV /root/nipe-scripts/esdmkv
ln -s /root/nipe-scripts/debian09/HardwareInfoGráfica /root/nipe-scripts/hardigra
ln -s /root/nipe-scripts/debian09/HardwareInfoRed /root/nipe-scripts/hardired
ln -s /root/nipe-scripts/debian09/ImportarBaseDeDatos /root/nipe-scripts/ibdd
ln -s /root/nipe-scripts/debian09/LanzarEscritorio /root/nipe-scripts/escritorio
ln -s /root/nipe-scripts/debian09/ListarNodosTORQueEntran /root/nipe-scripts/lisnodtor
ln -s /root/nipe-scripts/debian09/MonitorizarLog /root/nipe-scripts/monlog
ln -s /root/nipe-scripts/debian09/MostrarAparatosConectadosEnLaInterfaz /root/nipe-scripts/maceli
ln -s /root/nipe-scripts/debian09/MostrarIPLAN /root/nipe-scripts/iplan
ln -s /root/nipe-scripts/debian09/MostrarIPWAN /root/nipe-scripts/ipwan
ln -s /root/nipe-scripts/debian09/MostrarMódulosCargados /root/nipe-scripts/mosmodcar
ln -s /root/nipe-scripts/debian09/MostrarReglasIPTablesActivas /root/nipe-scripts/mosipt
ln -s /root/nipe-scripts/debian09/MostrarVersiónDeDebian /root/nipe-scripts/ver
ln -s /root/nipe-scripts/debian09/NotificarFalloDeDisco /root/nipe-scripts/nofadis
ln -s /root/nipe-scripts/debian09/NuevaWebVarWWW /root/nipe-scripts/nuevawebvar
ln -s /root/nipe-scripts/debian09/Reiniciar /root/nipe-scripts/rei
ln -s /root/nipe-scripts/debian09/RepararPermisosVarWWW /root/nipe-scripts/permweb
ln -s /root/nipe-scripts/debian09/RPMDeDisco /root/nipe-scripts/rpmdis
ln -s /root/nipe-scripts/debian09/SincronizarNiPeScripts /root/nipe-scripts/sinnps
ln -s /root/nipe-scripts/debian09/TRIM /root/nipe-scripts/trim
ln -s /root/nipe-scripts/debian09/UsuarioNuevoConShell /root/nipe-scripts/usunushell
ln -s /root/nipe-scripts/debian09/UsuarioNuevoSinShell /root/nipe-scripts/usununoshell
ln -s /root/nipe-scripts/debian09/Usuarios /root/nipe-scripts/usu
ln -s /root/nipe-scripts/debian09/VelocidadDeDiscoDeSistema /root/nipe-scripts/vddds
ln -s /root/nipe-scripts/debian09/VerEstadoDeServicio /root/nipe-scripts/servicio
ln -s /root/nipe-scripts/debian09/WinDir /root/nipe-scripts/windir

echo ""
echo "-------------------------------------------------------------------------"
echo "  ALIAS CREADOS."
echo "  DEBERÍAS PODER EJECUTAR LOS SCRIPTS ESCRIBIENDO EL NOMBRE DE SU ALIAS"
echo "-------------------------------------------------------------------------"
echo ""

