#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#----------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA EJECUTAR TAREAS CRON UNA VEZ POR HORA
#----------------------------------------------------------------

fechadeejecucion=$(date +A%YM%mD%d@%T)
chmod +x /root/TareasUnaVezPorHora

echo ""
echo "-------------------------------------------"
echo "  AGREGANDO EL SCRIPT /etc/cron.hourly..."
echo "-------------------------------------------"
echo ""
ln -s /root/syscripts/debian09/CronHorario /etc/cron.hourly/tareas

echo ""
echo "--------------------------------------"
echo "  EJECUTANDO TAREAS CRON HORARIAS..."
echo "--------------------------------------"
echo ""
/root/TareasUnaVezPorHora

echo ""
echo "--------------------"
echo "  GUARDANDO LOG..."
echo "--------------------"
echo ""
echo "Cron horario ejecutado el $fechadeejecucion ." >> /var/log/CronHorario.log

