#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#---------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA EJECUTAR TAREAS CRON UNA VEZ POR MES
#---------------------------------------------------------------

fechadeejecucion=$(date +A%YM%mD%d@%T)
chmod +x /root/TareasUnaVezPorMes

echo ""
echo "--------------------------------------------"
echo "  AGREGANDO EL SCRIPT /etc/cron.monthly..."
echo "--------------------------------------------"
echo ""
ln -s /root/syscripts/debian09/CronMensual /etc/cron.monthly/tareas

echo ""
echo "---------------------------------------"
echo "  EJECUTANDO TAREAS CRON MENSUALES..."
echo "---------------------------------------"
echo ""
/root/TareasUnaVezPorMes

echo ""
echo "--------------------"
echo "  GUARDANDO LOG..."
echo "--------------------"
echo ""
echo "Cron mensual ejecutado el $fechadeejecucion ." >> /var/log/CronMensual.log

