#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#----------------------------------------------------------------------------------------------
#  Script de NiPeGun para dejar sólo el último kernel estable en los repositorios de Debian 9
#----------------------------------------------------------------------------------------------

echo ""
echo "  Borrando todos los Kernels..."
echo ""
apt-get -y purge linux-image* linux-headers*

echo ""
echo "  Actualizando la lista de paquetes disponibles en los repositorios..."
echo ""
apt-get -y update

echo ""
echo "  Borrando /boot/* ..."
echo ""
rm -f /boot/*

echo ""
echo "  Instalando el último kernel..."
echo ""
apt-get -y install linux-image-amd64

VersUltKern=$(ls /boot | grep vmlinuz | awk -F'z-' '{print $2}')

echo ""
echo "  Creando el nuevo initrd..."
echo ""
update-initramfs -v -c -k $VersUltKern

echo ""
echo "  Actualizando el nuevo initrd..."
echo ""
update-initramfs -v -u -k $VersUltKern

echo ""
echo "  Re-instalando grub..."
echo ""
grub-install --recheck /dev/sda

echo ""
echo "  Actualizando grub..."
echo ""
update-grub

