#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#---------------------------------------------------
#  SCRIPT DE NIPEGUN PARA PREPARAR LAS TAREAS CRON
#---------------------------------------------------

echo ""
echo "-----------------------------------------------"
echo "  CREANDO EL ARCHIVO PARA LAS TAREAS HORARIAS"
echo "-----------------------------------------------"
echo ""
echo '#!/bin/bash' > /root/TareasCronPorHora
echo "" >> /root/TareasCronPorHora
echo 'FechaDeEjecucion=$(date +A%YM%mD%d@%T)' >> /root/TareasCronPorHora
echo 'echo "Cron horario ejecutado el $FechaDeEjecucion" >> /var/log/TareasCronPorHora.log' >> /root/TareasCronPorHora
echo "" >> /root/TareasCronPorHora
echo "  ESCRIBE ABAJO, UNA POR LÍNEA, LAS TAREAS A EJECUTAR CADA HORA"  >> /root/TareasCronPorHora
echo "▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼" >> /root/TareasCronPorHora
echo "" >> /root/TareasCronPorHora

echo ""
echo "-----------------------------------------"
echo "  DANDO PERMISO DE EJECUCIÓN AL ARCHIVO"
echo "-----------------------------------------"
echo ""
chmod +x /root/TareasCronPorHora

echo ""
echo "--------------------------------------------------------"
echo "  CREANDO ENLACE HACIA EL ARCHIVO EN /etc/cron.hourly/"
echo "--------------------------------------------------------"
echo ""
ln -s /root/TareasCronPorHora /etc/cron.hourly/TareasCronPorHora

echo ""
echo "-------------------------------------------------------------"
echo ""

echo ""
echo "----------------------------------------------"
echo "  CREANDO EL ARCHIVO PARA LAS TAREAS DIARIAS"
echo "----------------------------------------------"
echo ""
echo '#!/bin/bash' > /root/TareasCronPorDía
echo "" >> /root/TareasCronPorDía
echo 'FechaDeEjecucion=$(date +A%YM%mD%d@%T)' >> /root/TareasCronPorDía
echo 'echo "Cron diario ejecutado el $FechaDeEjecucion" >> /var/log/TareasCronPorDía.log' >> /root/TareasCronPorDía
echo "" >> /root/TareasCronPorDía
echo "  ESCRIBE ABAJO, UNA POR LÍNEA, LAS TAREAS A EJECUTAR CADA DÍA"  >> /root/TareasCronPorDía
echo "▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼" >> /root/TareasCronPorDía
echo "" >> /root/TareasCronPorDía

echo ""
echo "-----------------------------------------"
echo "  DANDO PERMISO DE EJECUCIÓN AL ARCHIVO"
echo "-----------------------------------------"
echo ""
chmod +x /root/TareasCronPorDía

echo ""
echo "-------------------------------------------------------"
echo "  CREANDO ENLACE HACIA EL ARCHIVO EN /etc/cron.daily/"
echo "-------------------------------------------------------"
echo ""
ln -s /root/TareasCronPorDía /etc/cron.daily/TareasCronPorDía

echo ""
echo "-------------------------------------------------------------"
echo ""

echo ""
echo "------------------------------------------------"
echo "  CREANDO EL ARCHIVO PARA LAS TAREAS SEMANALES"
echo "------------------------------------------------"
echo ""
echo '#!/bin/bash' > /root/TareasCronPorSemana
echo "" >> /root/TareasCronPorSemana
echo 'FechaDeEjecucion=$(date +A%YM%mD%d@%T)' >> /root/TareasCronPorSemana
echo 'echo "Cron semanal ejecutado el $FechaDeEjecucion" >> /var/log/TareasCronPorSemana.log' >> /root/TareasCronPorSemana
echo "" >> /root/TareasCronPorSemana
echo "  ESCRIBE ABAJO, UNA POR LÍNEA, LAS TAREAS A EJECUTAR CADA SEMANA"  >> /root/TareasCronPorSemana
echo "▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼" >> /root/TareasCronPorSemana
echo "" >> /root/TareasCronPorSemana

echo ""
echo "-----------------------------------------"
echo "  DANDO PERMISO DE EJECUCIÓN AL ARCHIVO"
echo "-----------------------------------------"
echo ""
chmod +x /root/TareasCronPorSemana

echo ""
echo "--------------------------------------------------------"
echo "  CREANDO ENLACE HACIA EL ARCHIVO EN /etc/cron.weekly/"
echo "--------------------------------------------------------"
echo ""
ln -s /root/TareasCronPorSemana /etc/cron.weekly/TareasCronPorSemana

echo ""
echo "-------------------------------------------------------------"
echo ""

echo ""
echo "------------------------------------------------"
echo "  CREANDO EL ARCHIVO PARA LAS TAREAS MENSUALES"
echo "------------------------------------------------"
echo ""
echo '#!/bin/bash' > /root/TareasCronPorMes
echo "" >> /root/TareasCronPorMes
echo 'FechaDeEjecucion=$(date +A%YM%mD%d@%T)' >> /root/TareasCronPorMes
echo 'echo "Cron mensual ejecutado el $FechaDeEjecucion" >> /var/log/TareasCronPorMes.log' >> /root/TareasCronPorMes
echo "" >> /root/TareasCronPorMes
echo "  ESCRIBE ABAJO, UNA POR LÍNEA, LAS TAREAS A EJECUTAR CADA MES"  >> /root/TareasCronPorMes
echo "▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼" >> /root/TareasCronPorMes
echo "" >> /root/TareasCronPorMes

echo ""
echo "-----------------------------------------"
echo "  DANDO PERMISO DE EJECUCIÓN AL ARCHIVO"
echo "-----------------------------------------"
echo ""
chmod +x /root/TareasCronPorMes

echo ""
echo "---------------------------------------------------------"
echo "  CREANDO ENLACE HACIA EL ARCHIVO EN /etc/cron.monthly/"
echo "---------------------------------------------------------"
echo ""
ln -s /root/TareasCronPorMes /etc/cron.monthly/TareasCronPorMes

