#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#----------------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA REPARAR LOS PERMISOS DE LA CARPETA /var/www
#----------------------------------------------------------------------

# Asignar propiedad de todo el contenido al usuario www-data
echo ""
chown www-data:www-data /var/www -R
echo "..."

# Poner los permisos correctos a carpetas
echo ""
find /var/www -type d -exec chmod 755 {} \;
echo "..."

# Poner los permisos correctos a archivos
echo ""
find /var/www -type f -exec chmod 644 {} \;
echo "..."

# Asignar la propiedad de /var/root al usuario root. (Necesario para enjaular Webs por SFTP)
echo ""
chown root:root /var/www
echo "..."

echo ""
echo "Finalizado"
echo ""

