#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA SINCRONIZAR LOS DEB-SCRIPTS
#------------------------------------------------------

echo ""
echo "-----------------------------------------------------------"
echo "  SINCRONIZANDO LOS DEB-SCRIPTS CON LAS ÚLTIMAS VERSIONES"
echo "    Y DESCARGANDO NUEVOS DEB-SCRIPTS SI ES QUE EXISTEN"
echo "-----------------------------------------------------------"
echo ""
rm /root/deb-scripts -R
cd /root
git clone --depth=1 https://github.com/nipegun/deb-scripts
rm /root/deb-scripts/.git -R
rm /root/deb-scripts/*
chmod +x /root/deb-scripts/* -R
/root/deb-scripts/debian09/CrearAlias

echo ""
echo "-------------------------------------------"
echo "  DEB-SCRIPTS SINCRONIZADOS CORRECTAMENTE"
echo "-------------------------------------------"
echo ""

