#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#----------------------------------------------------
#  SCRIPT DE NIPEGUN PARA SINCRONIZAR LOS SYSCRIPTS
#----------------------------------------------------

echo ""
echo "---------------------------------------------------------"
echo "  SINCRONIZANDO LOS SYSCRIPTS CON LAS ÚLTIMAS VERSIONES"
echo "    Y DESCARGANDO NUEVOS SYSCRIPTS SI ES QUE EXISTEN"
echo "---------------------------------------------------------"
echo ""

rm /root/syscripts -R
cd /root
git clone --depth=1 https://github.com/nipegun/syscripts
rm /root/syscripts/.git -R
rm /root/syscripts/*
chmod +x /root/syscripts/* -R
/root/syscripts/debian08/CrearAlias

