#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-------------------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA CREAR LOS ALIAS DE LOS SYSCRIPTS PARA DEBIAN 8
#-------------------------------------------------------------------------

echo ""
echo "---------------------------------------"
echo "  CREANDO ALIAS PARA LOS SYSCRIPTS..."
echo "---------------------------------------"
echo ""

ln -s /root/syscripts/debian8/externos/VelocidadDeInternet /root/syscripts/vdi

ln -s /root/syscripts/debian8/SincronizarNiPeScripts /root/syscripts/scnps
ln -s /root/syscripts/debian8/HardwareInfoGrafica /root/syscripts/hingra

echo ""
echo "-------------------------------------------------------------------------"
echo "  ALIAS CREADOS:"
echo "  DEBERÍAS PODER EJECUTAR LOS SCRIPTS ESCRIBIENDO EL NOMBRE DE SU ALIAS"
echo "-------------------------------------------------------------------------"
echo ""
