#!/bin/bash

#
# Usar AgregarAtributoExtendidoAArchivoOCarpeta Ruta TítuloAtributo Texto
#
# Ejemplo:
# AgregarAtributoExtendidoAArchivoOCarpeta ~/Desktop/Prueba password "El perro salió de viaje"

xattr -w $2 $3 $1

