#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-------------------------------------------------------------------------------------
#  Script de NiPeGun para modificr una MV Base para adaptarla a una nueva MV Clonada
#
#  Este script debe correr dentro de una máquina virtual de ProxmoxVE
#-------------------------------------------------------------------------------------

CantArgsEsperados=2
ArgsInsuficientes=65

ColorRojo='\033[1;31m'
ColorVerde='\033[1;32m'
FinColor='\033[0m'

if [ $# -ne $CantArgsEsperados ]
  then
    echo ""
    echo "------------------------------------------------------------------------------"
    echo -e "${ColorRojo}Mal uso del script.${FinColor} El uso correcto sería:"
    echo ""
    echo -e "  $0 ${ColorVerde}[NombreDeLaNuevaMV] [NombreDelUsuarioNoRoot]${FinColor}"
    echo ""
    echo "Ejemplo:"
    echo ""
    echo "  $0 debianpepe pepe"
    echo "------------------------------------------------------------------------------"
    echo ""
    exit $ArgsInsuficientes
  else
    echo ""
    echo "Cambiando el nombre de la MV a $1"
    echo ""
    find /bin        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /boot       -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /dev        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /etc        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /home       -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /lib        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /lib64      -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /lost+found -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /media      -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /mnt        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /opt        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /root       -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /run        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /sbin       -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /srv        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /tmp        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /usr        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    find /var        -type f -exec sed -i -e "s|DebianBase|$1|g" {} \;
    
    echo ""
    echo "Poniendo todos los logs a cero..."
    echo ""
    find /var/log/   -type f -exec truncate -s 0 {} \;
    
    echo ""
    echo "Cambiando el nombre y la carpeta del usuario no root..."
    echo ""
    usermod -l $2 usuario
    usermod -d /home/$2 -m $2
    groupmod -n $2 usuario
    echo ""
    echo "Nombre cambiado:"
    echo "Nuevo nombre: $2"
    echo "Nuevo password: $2"
    echo ""
fi
