#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#--------------------------------------------
#  SCRIPT DE NIPEGUN PARA ACTUALIZAR DEBIAN
#--------------------------------------------

echo ""
echo "----------------------------------------"
echo "  ACTUALIZANDO EL SISTEMA OPERATIVO..."
echo "----------------------------------------"
echo ""
apt-get -y update
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get -y autoremove

echo ""
echo "-----------------------------------"
echo "  EJECUCIÓN DEL SCRIPT FINALIZADA"
echo "-----------------------------------"
echo ""
