#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#--------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA ENVIAR MAIL EN UNA SOLA LÍNEA
#  PAQUETES ACONSEJADOS A INSTALAR ANTES:
#  postfix mailutils
#--------------------------------------------------------

EXPECTED_ARGS=3
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
  then
    echo ""
    echo "------------------------------------------------------------------------------"
    echo "Mal uso del script."
    echo ""
    echo "El uso correcto sería: $0 DirecciónDeCorreo Asunto Texto"
    echo ""
    echo "Ejemplo:"
    echo ' $0 pepe@pepe.com "Recordatorio de cita" "Acuérdate que quedamos para comer"'
    echo "------------------------------------------------------------------------------"
    echo ""
    exit $E_BADARGS
  else
    echo "$3" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "$2" $1
fi

