#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-----------------------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA AUTOMATIZAR LA PREPARACIÓN DE PROXMOXVE A MI GUSTO
#-----------------------------------------------------------------------------

/root/prox-scripts/proxmoxve05/UnicaEjecucion/1-PrepararParaPoderActualizar
/root/prox-scripts/proxmoxve05/UnicaEjecucion/2-PonerPVEEnEspañol
/root/prox-scripts/proxmoxve05/UnicaEjecucion/3-PrepararComandosPostArranque
/root/prox-scripts/proxmoxve05/UnicaEjecucion/4-PrepararTareasCron
/root/prox-scripts/proxmoxve05/UnicaEjecucion/5-DescargarContainersALocal
/root/prox-scripts/apve
/root/prox-scripts/proxmoxve05/UnicaEjecucion/5-InstalarEntornoGráfico

