#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#----------------------------------------------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA PREPARAR PROXMOXVE DE FORMA QUE PUEDA SER ACTUALIZADO POR NO-SUSCRIPTORES 
#----------------------------------------------------------------------------------------------------

echo ""
echo "--------------------------------------------"
echo "  DESHABILITANDO EL REPOSITORIO ENTERPRISE"
echo "--------------------------------------------"
echo ""
cp /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.bak
sed -i -e 's|deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise|# deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise|g' /etc/apt/sources.list.d/pve-enterprise.list

echo ""
echo "-------------------------------------------------"
echo "  AGREGANDO EL REPOSITORIO PARA NO-SUSCRIPTORES"
echo "-------------------------------------------------"
echo ""
echo "deb http://download.proxmox.com/debian/pve stretch pve-no-subscription" > /etc/apt/sources.list.d/pve-no-sub.list

echo ""
echo "----------------------------"
echo "  ACTIVANDO CAMBIOS EN APT"
echo "----------------------------"
echo ""
apt-get -y update

