#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-----------------------------------------------------
#  SCRIPT DE NIPEGUN PARA PONER PROXMOXVE EN ESPAÑOL
#-----------------------------------------------------

# Actualizar
apt-get -y update

# Activar el locale en español de España UTF-8 descomentando
# la línea que empiece por "# es_ES.UTF-8" en /etc/locale.gen
sed -i 's/^# *\(es_ES.UTF-8\)/\1/' /etc/locale.gen

# Generar los nuevos locales activados en /etc/locale.gen
locale-gen

# Modificar el archivo /etc/default/locale reflejando los cambios
echo -e 'LANG="es_ES.UTF-8"\nLANGUAGE="es_ES:es"\n' > /etc/default/locale

echo ""
echo "---------------------------------------------------------------------"
echo "  IDIOMA DEL SISTEMA CAMBIADO."
echo "  ES NECESARIO CERRAR LA SESIÓN PARA QUE LOS CAMBIOS SURJAN EFECTO."
echo "---------------------------------------------------------------------"
echo ""

