#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#----------------------------------------------------------
#  Script de NiPeGun para parchear el apagado ACPI de DSM
#----------------------------------------------------------


cd /bin
wget --no-check-certificate http://hacks4geeks.com/_/premium/descargas/dsm/6.1.4/acpishutdown/bin/acpid

cd /etc/acpi
wget --no-check-certificate http://hacks4geeks.com/_/premium/descargas/dsm/6.1.4/acpishutdown/etc/acpi/powerbtn.sh

cd /etc/acpi/events
wget --no-check-certificate http://hacks4geeks.com/_/premium/descargas/dsm/6.1.4/acpishutdown/etc/acpi/events/powerbtn-conf

cd /lib/modules/
wget --no-check-certificate http://hacks4geeks.com/_/premium/descargas/dsm/6.1.4/acpishutdown/lib/modules/button.ko
wget --no-check-certificate http://hacks4geeks.com/_/premium/descargas/dsm/6.1.4/acpishutdown/lib/modules/evdev.ko

cd /usr/local/etc/rc.d
wget --no-check-certificate http://hacks4geeks.com/_/premium/descargas/dsm/6.1.4/acpishutdown/usr/local/etc/rc.d/S30acpid.sh

