#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-----------------------------------------------
#  Script de NiPeGun para actualizar ProxmoxVE
#-----------------------------------------------

echo ""
echo "-----------------------------"
echo "  Actualizando ProxmoxVE..."
echo "-----------------------------"
echo ""
apt-get -y update
apt-get -y dist-upgrade
apt-get -y autoremove

echo ""
echo "-----------------------------------"
echo "  Ejecución de script finalizada"
echo "-----------------------------------"
echo ""

