#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-------------------------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA CREAR LOS ALIAS DE LOS PROX-SCRIPTS PARA PROXMOXVE 5
#-------------------------------------------------------------------------------

echo ""
echo "------------------------------------------"
echo "  CREANDO ALIAS PARA LOS NIPE-SCRIPTS..."
echo "------------------------------------------"
echo ""

ln -s /root/nipe-scripts/proxmoxve05/AbrirMidnightCommander /root/nipe-scripts/amc
ln -s /root/nipe-scripts/proxmoxve05/ActualizarProxmoxVirtualEnvironment /root/nipe-scripts/apve
ln -s /root/nipe-scripts/proxmoxve05/CarpetaDeISOs /root/nipe-scripts/isos
ln -s /root/nipe-scripts/proxmoxve05/EditarVM /root/nipe-scripts/edvm
ln -s /root/nipe-scripts/proxmoxve05/MostrarLaVersiónDePVE /root/nipe-scripts/ver
ln -s /root/nipe-scripts/proxmoxve05/SincronizarProxScripts /root/nipe-scripts/sinps
ln -s /root/nipe-scripts/proxmoxve05/TRIM /root/nipe-scripts/trim

echo ""
echo "-------------------------------------------------------------------------"
echo "  ALIAS CREADOS:"
echo "  DEBERÍAS PODER EJECUTAR LOS SCRIPTS ESCRIBIENDO EL NOMBRE DE SU ALIAS"
echo "-------------------------------------------------------------------------"
echo ""
