#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-------------------------------------------------------
#  Script de NiPeGun para instalar Atom en Debian 9
#-------------------------------------------------------

echo ""
echo "  Instalando Atom..."
echo ""
mkdir -p /root/paquetes/atom
cd /root/paquetes/atom
URLArchivoDebConTag=$(curl --silent  https://github.com/atom/atom/releases/latest | cut -d\" -f2)

firstString="I love Suzi and Marry"
PalabraAReemplazar="download"
URLArchivoDeb="${URLArchivoDebConTag/tag/$PalabraAReemplazar}" 

echo $URLArchivoDeb
#wget --no-check-certificate $URLArchivoDeb/download/atom-amd64.deb
#gdebi atom-amd64.deb

