#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-----------------------------------------------------
#  Script de NiPeGun para instalar Steam en Debian 9
#-----------------------------------------------------

echo ""
echo "  Instalando Steam..."
echo ""
apt-get -y update
apt-get -y install wget gdebi
mkdir -p /root/paquetes/steam
cd /root/paquetes/steam
wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb
gdebi /root/paquetes/steam/steam.deb
apt-get -y install libgl1-mesa-dri libgl1-mesa-glx libc6 
