#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#-------------------------------------------------------
#  Script de NiPeGun para instalar Dropbox en Debian 9
#-------------------------------------------------------

echo ""
echo "  Creando la carpeta para descargar el paquete..."
echo ""
mkdir -p ~/paquetes/dropbox/

echo ""
echo "  Descargando el paquete desde la web de Dropbox..."
echo ""
wget -O ~/paquetes/dropbox/dropbox.tar https://www.dropbox.com/download?plat=lnx.x86_64

echo ""
echo "  Descomprimiento el paquete..."
echo ""
tar xzf ~/paquetes/dropbox/dropbox.tar -C ~/

echo ""
echo "  Descargando el script de python para controlar Dropbox desde la terminal"
echo ""
wget -O ~/DemonioDropbox "https://www.dropbox.com/download?dl=packages/dropbox.py"
chmod +x ~/DemonioDropbox

echo ""
echo "  Arrancando el daemon por primera vez..."
echo ""
~/.dropbox-dist/dropboxd
echo ""

