#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#------------------------------------------------------------------------------------------------
#  Script de NiPeGun para instalar y preparar la compartición remota del escritorio en Debian 9
#------------------------------------------------------------------------------------------------



echo ""
echo "  Instalando el servidor xrdp..."
echo ""
apt-get -y update
apt-get -y install xrdp

echo ""
echo "  Activando XRDP como servicio..."
echo ""
systemctl enable xrdp

# Ubuntu 18.04

# Instalar Gnome Tweak Tool
sudo apt-get -y install gnome-tweak-tool
# Permitir el acceso a la consola
sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
# Crear políticas de excepción
echo "[Allow Colord all Users]" > /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
echo "Identity=unix-user:*" >> /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
echo "Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile" >> /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
echo "ResultAny=no" >> /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
echo "ResultInactive=no" >> /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
echo "ResultActive=yes" >> /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
# Activar las extensiones de Gnome Shell
gnome-shell-extension-tool -e ubuntu-dock@ubuntu.com
gnome-shell-extension-tool -e ubuntu-appindicators@ubuntu.com
# Vaciar la carpeta de crashes
sudo rm /var/crash/*

echo ""
echo "  Ejecución del script, finalizada."
echo ""
echo "  Después de reiniciar el sistema deberías poder"
echo "  conectarte a su escritorio remoto desde otro ordenador."
echo ""

