#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#------------------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA VOLVER LOS NOMBRES DE LAS INTERFACES ETHERNET
#  A LA NOMENCLATURA VIEJA USADA EN DEBIAN 8 
#------------------------------------------------------------------------

echo ""
echo "---------------------------------------------------"
echo "  CAMBIANDO EL NOMBRE DE LAS INTERFACES DE RED..."
echo "---------------------------------------------------"
echo ""
sudo -i -e 's|GRUB_CMDLINE_LINUX=""|GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"|g' /etc/default/grub

echo ""
echo "--------------------------------------------"
echo "  ACORTANDO EL TIEMPO DE ESPERA DE GRUB..."
echo "--------------------------------------------"
echo ""
sed -i -e "s|GRUB_TIMEOUT=5|GRUB_TIMEOUT=1|g" /etc/default/grub

echo ""
echo "------------------------"
echo "  ACTUALIZANDO GRUB..."
echo "------------------------"
echo ""
update-grub

