#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#------------------------------------------------------------------------
#  Script de NiPeGun para crear el archivo con los comandos de IPTables
#  que se ejecutarán cada vez que se inicie el sistema
#------------------------------------------------------------------------

echo ""
echo "----------------------------------------------"
echo "  CREANDO EL ARCHIVO PARA METER LOS COMANDOS"
echo "----------------------------------------------"
echo ""
echo '#!/bin/bash' > /root/ComandosIPTables
echo "" >> /root/ComandosIPTables
echo "#  ESCRIBE ABAJO, UNO POR LÍNEA, LOS COMANDOS DE IPTABLES A EJECUTAR AL ARRANQUE"  >> /root/ComandosIPTables
echo "#▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼" >> /root/ComandosIPTables
echo "" >> /root/ComandosIPTables
chmod +x /root/ComandosIPTables
echo "/root/ComandosIPTables" >> /root/ComandosPostArranque

