#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#--------------------------------------------------------------------
#  Script de NiPeGun para instalar el lenguaje de prograación Swift
#--------------------------------------------------------------------

apt-get -y install curl
mkdir /opt/swift
cd /opt/swift/
SwiftURL=$(curl --silent https://swift.org/download/ | grep -v DEVELOPMENT | grep -v SNAPSHOT | grep -v Signature | grep ubuntu 16.10)
echo $SwiftURL
#wget $SwiftURL
