#!/bin/bash

# Pongo a disposición pública este script bajo el término de "software
# de dominio público". Puedes hacer lo que te salga de los huevos con él
# porque es libre de verdad; no libre con condiciones como las licencias GNU
# y otras patrañas similares. Si se te llena la boca hablando de libertad
# entonces hazlo realmente libre. No tienes que aceptar ningún tipo de términos
# de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

#------------------------------------------------------------------
#  SCRIPT DE NIPEGUN PARA INSTALAR Y CONFIGURAR EL SERVIDOR PLEX
#-------------------------------------------------------------------

menu=(dialog --timeout 5 --checklist "Elección de la arquitectura:" 22 76 16)
  opciones=(1 "Instalar o actualizar versión de 32 bits" off
            2 "Instalar o actualizar versión de 64 bits" off)
  choices=$("${menu[@]}" "${opciones[@]}" 2>&1 >/dev/tty)
  clear

  for choice in $choices

    do

      case $choice in

        1)
          echo ""
          echo "Instalando Plex para arquitectura x86 de 32 bits..."
          echo ""
          mkdir /root/paquetes
          mkdir /root/paquetes/plex 
          cd /root/paquetes/plex
          rm -f /root/paquetes/plex/plex32x86.deb

          echo ""
          echo "Descargando el paquete de instalación..."
          echo ""
          wget http://hacks4geeks.com/_/premium/descargas/debian/root/paquetes/plex/plex32x86.deb

          echo ""
          echo "Deteniendo el servicio plexmediaserver (si es que está activo)..."
          echo ""
          service plexmediaserver stop

          echo ""
          echo ""
          echo ""
          dpkg -i /root/paquetes/plex/plex32x86.deb
          
          echo ""
          echo "Arrancando el servicio plexmediaserver..."
          echo ""
          service plexmediaserver start
        ;;

        2)
          echo ""
          echo "Instalando Plex para arquitectura x86 de 64 bits..."
          echo ""
          mkdir /root/paquetes
          mkdir /root/paquetes/plex 
          cd /root/paquetes/plex
          rm -f /root/paquetes/plex/plex64x86.deb

          echo ""
          echo "Descargando el paquete de instalación..."
          echo ""
          wget http://hacks4geeks.com/_/premium/descargas/debian/root/paquetes/plex/plex64x86.deb

          echo ""
          echo "Deteniendo el servicio plexmediaserver (si es que está activo)..."
          echo ""
          service plexmediaserver stop

          echo ""
          echo ""
          echo ""
          dpkg -i /root/paquetes/plex/plex64x86.deb
          
          echo ""
          echo "Arrancando el servicio plexmediaserver..."
          echo ""
          service plexmediaserver start
        ;;

        3)
          echo ""
          echo "Instalando Plex para arquitectura ARMv7..."
          echo ""
          mkdir /root/paquetes
          mkdir /root/paquetes/plex 
          cd /root/paquetes/plex
          rm -f /root/paquetes/plex/plexARMv7.deb

          echo ""
          echo "Descargando el paquete de instalación..."
          echo ""
          wget http://hacks4geeks.com/_/premium/descargas/debian/root/paquetes/plex/plexARMv7.deb

          echo ""
          echo "Deteniendo el servicio plexmediaserver (si es que está activo)..."
          echo ""
          service plexmediaserver stop

          echo ""
          echo ""
          echo ""
          dpkg -i /root/paquetes/plex/plexARMv7.deb
          
          echo ""
          echo "Arrancando el servicio plexmediaserver..."
          echo ""
          service plexmediaserver start
        ;;

        4)
          echo ""
          echo "Instalando Plex para arquitectura ARMv8..."
          echo ""
          mkdir /root/paquetes
          mkdir /root/paquetes/plex 
          cd /root/paquetes/plex
          rm -f /root/paquetes/plex/plexARMv8.deb

          echo ""
          echo "Descargando el paquete de instalación..."
          echo ""
          wget http://hacks4geeks.com/_/premium/descargas/debian/root/paquetes/plex/plexARMv8.deb

          echo ""
          echo "Deteniendo el servicio plexmediaserver (si es que está activo)..."
          echo ""
          service plexmediaserver stop

          echo ""
          echo ""
          echo ""
          dpkg -i /root/paquetes/plex/plexARMv8.deb
          
          echo ""
          echo "Arrancando el servicio plexmediaserver..."
          echo ""
          service plexmediaserver start
        ;;


      esac

done

